#ifndef MEDNUSAUISETTINGS_H
#define MEDNUSAUISETTINGS_H

#define LESSONPANEL_WIDTH 300
#define LESSONPANEL_BORDER 5
#define LESSONPANEL_HEIGHT 194
#define LESSONPANEL_CLICKHEIGHT 64
#define LESSONPANEL_CONTRACTED_CLICKHEIGHT 24
#define TOPBAR_HEIGHT 40
#define SIDEBAR_OFFSET 10
#define LOGO_WIDTH 160

#endif // MEDNUSAUISETTINGS_H
