#ifndef MEDNUSAUISETTINGS_H
#define MEDNUSAUISETTINGS_H

#define LESSONPANEL_WIDTH 300
#define LESSONPANEL_BORDER 5
#define LESSONPANEL_BORDERICON 15
#define LESSONPANEL_HEIGHT 176
#define LESSONPANEL_CLICKHEIGHT 64
#define LESSONPANEL_CONTRACTED_CLICKHEIGHT 24
#define TOPBAR_HEIGHT 40
#define SIDEBAR_OFFSET 14
#define LOGO_WIDTH 160

#define VIDEO_BORDER 10
#define VIDEO_SEP_LENGTH 7
#define VIDEO_TIME_LENGTH 50
#define VIDEO_ICON_SIZE 24

 #define MIN(a,b) ((a) < (b) ? (a) : (b))
 #define MAX(a,b) ((a) > (b) ? (a) : (b))

#endif // MEDNUSAUISETTINGS_H
